# Generated by Django 2.0.7 on 2018-07-26 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='FriendsPending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.CharField(max_length=30)),
                ('gender', models.CharField(default='none', max_length=10)),
                ('city', models.CharField(default='no-address', max_length=30)),
                ('state', models.CharField(default='no-state', max_length=30)),
                ('zip_code', models.CharField(default='00000000', max_length=10)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('friends', models.ManyToManyField(blank=True, null=True, to='users.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='friendspending',
            name='friendsPending',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
