# Generated by Django 2.0.7 on 2018-07-26 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='medias',
        ),
    ]
